stages:
  train_simple_conv:
    cmd:
      - rm -rf data/models/SIMPLE_CONV-dvc
      - python -m cnn_res_degrader.train -s dvc
    params:
      - SIMPLE_CONV
    deps:
      - data/proba-v11_shifted
      - cnn_res_degrader/data_loading.py
      - cnn_res_degrader/train.py
      - cnn_res_degrader/metrics.py
      - cnn_res_degrader/models/simple_conv.py
      - cnn_res_degrader/models/maskable_degrader.py
      - cnn_res_degrader/models/common.py
    outs:
      - data/models/SIMPLE_CONV-dvc

  train_autoencoder:
    cmd:
      - rm -rf data/models/AUTOENCODER-dvc
      - python -m cnn_res_degrader.train -a dvc
    params:
      - AUTOENCODER
    deps:
      - data/proba-v11_shifted
      - cnn_res_degrader/data_loading.py
      - cnn_res_degrader/train.py
      - cnn_res_degrader/metrics.py
      - cnn_res_degrader/models/autoencoder.py
      - cnn_res_degrader/models/maskable_degrader.py
      - cnn_res_degrader/models/common.py
    outs:
      - data/models/AUTOENCODER-dvc

  train_gan:
    cmd:
      - rm -rf data/models/AUTOENCODER-dvc
      - python -m cnn_res_degrader.train -g dvc
    params:
      - GAN
    deps:
      - data/proba-v11_shifted
      - cnn_res_degrader/data_loading.py
      - cnn_res_degrader/train.py
      - cnn_res_degrader/metrics.py
      - cnn_res_degrader/models/gan.py
      - cnn_res_degrader/models/common.py
    outs:
      - data/models/GAN-dvc
